services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - 6379

  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - pg_data:/var/liv/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: ./
    tty: true
    ports:
      - '8000:8000'
    command:
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  celery:
    build: ./
    tty: true
    command: celery -A post_app worker -l INFO
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app

  celery-beat:
    build: ./
    tty: true
    command: celery -A post_app beat -l INFO
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
      - celery

volumes:
  pg_data:
